#!/usr/bin/env python3
"""
Generate load_data.sql from all day input files.
Creates tables: day1_input, day2_input, etc.
"""

import os

def escape_sql(s):
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")

def generate_day_sql(day_num, input_path):
    """Generate SQL for a single day's input."""
    table_name = f"day{day_num}_input"

    lines = []
    lines.append(f"-- Day {day_num}")
    lines.append(f"DROP TABLE IF EXISTS {table_name};")
    lines.append(f"CREATE TABLE {table_name} (line_num INTEGER PRIMARY KEY, line TEXT);")

    with open(input_path, 'r') as f:
        data_lines = f.read().rstrip('\n').split('\n')

    if data_lines:
        lines.append(f"INSERT INTO {table_name} (line_num, line) VALUES")
        values = []
        for i, line in enumerate(data_lines, 1):
            escaped = escape_sql(line)
            values.append(f"  ({i}, '{escaped}')")
        lines.append(",\n".join(values) + ";")

    return "\n".join(lines)

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "load_data.sql")

    all_sql = ["-- Auto-generated by generate_data_sql.py", "-- Run: psql -d aoc < load_data.sql", ""]

    for day in range(1, 13):
        input_path = os.path.join(script_dir, f"day-{day}", "input")
        if os.path.exists(input_path):
            all_sql.append(generate_day_sql(day, input_path))
            all_sql.append("")

    with open(output_path, 'w') as f:
        f.write("\n".join(all_sql))

    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
